### ISSUE TITLE
an error related to pytorch_lightning in this project

### ISSUE THREAD

**Issue by Dsqds** [gitabtion/SoftMaskedBert-PyTorch#13]
The detection result is precision=0.033734939759036145, recall=0.7636363636363637 and F1=0.06461538461538462
The correction result is precision=0.0, recall=0.0 and F1=0
Sentence Level: acc:0.000000, precision:0.000000, recall:0.000000, f1:0.000000
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main()
  File "main.py", line 94, in main
    trainer.fit(model, train_loader, valid_loader)
  File "/home/containeruser/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in fit
    self.single_gpu_train(model)
  File "/home/containeruser/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 176, in single_gpu_train
    self.run_pretrain_routine(model)
  File "/home/containeruser/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1077, in run_pretrain_routine
    _, _, _, callback_metrics, _ = self.process_output(eval_results)
  File "/home/containeruser/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/logging.py", line 106, in process_output
    for k, v in output.items():
AttributeError: 'NoneType' object has no attribute 'items'

i think this error is strange and i don't knon how to trace it because the interface is only 'trainer.fit'.
i think maybe you had met this problem.

**Comment by gitabtion** [comment]
This error is caused by the encoding problem of the data, it fixed by my another project [BertBasedCorrectionModels](https://github.com/gitabtion/BertBasedCorrectionModels), you can use that project to process the data, and than copy to this project.

**Comment by gitabtion** [comment]
i will fix this issue soon, thanks.
