### ISSUE TITLE
python main.py --mode preproc时报错

### ISSUE THREAD

**Issue by Angel-spz** [gitabtion/SoftMaskedBert-PyTorch#17]
错误如下：
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main()
  File "main.py", line 58, in main
    preproc()
  File "/u01/isi/SoftMaskedBert-PyTorch-main/src/data_processor.py", line 183, in preproc
    rst_items += proc_item(item, convertor)
  File "/u01/isi/SoftMaskedBert-PyTorch-main/src/data_processor.py", line 13, in proc_item
    root = etree.XML(item)
  File "src/lxml/etree.pyx", line 3216, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Unescaped '<' not allowed in attributes values, line 1, column 32

在网上查了好久也没有解决，想问一下是什么问题？谢谢。

**Comment by gitabtion** [comment]
先确定下载的文件有没有出问题，如果没问题的话用我另一个项目BertBasedCorrectionModels的数据处理脚本试试。
